# Generated by Django 4.2.7 on 2024-01-09 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='CSVFilePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_number_of_keys', models.IntegerField(blank=True, null=True)),
                ('end_number_of_keys', models.IntegerField(blank=True, null=True)),
                ('array', models.CharField(blank=True, max_length=10, null=True)),
                ('row_number', models.CharField(blank=True, max_length=20, null=True)),
                ('column_number', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('trials', models.IntegerField(blank=True, null=True)),
                ('csv_name', models.CharField(blank=True, max_length=200, null=True)),
                ('csv_random_number', models.IntegerField(blank=True, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_keys', models.IntegerField(blank=True, null=True)),
                ('pattern', models.TextField(blank=True, null=True)),
                ('trials', models.IntegerField(blank=True, null=True)),
                ('time_use', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('csv_name', models.TextField(blank=True, default='-', null=True)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.testcontrol')),
            ],
        ),
        migrations.CreateModel(
            name='RandomTestControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random', models.CharField(max_length=100, null=True)),
                ('level', models.IntegerField(null=True)),
                ('round', models.IntegerField(null=True)),
                ('csv_name', models.CharField(max_length=200, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
            ],
        ),
    ]
