# Generated by Django 4.2.7 on 2024-01-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcontrol',
            name='test_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
