# Generated by Django 4.2.7 on 2024-01-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_person_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
